#file = "auto_bits_generated.h"
prefix = "bit"
list = [ "0", "1", "2", "3" ]
auto_bits_add(prefix, list)
#auto_bits_add(prefix, list, file)

prefix = "flag"
list = [ "A", "B", "C", "D" ]
auto_bits_add(prefix, list)

@prespace = 0
@target_tab_column = 5
notify("|g|[check mark]|n demake/auto_bits.rb is present - generating code")

=begin

The default configuration above generates the following C code
in the file auto_bits_generated.h:

/*

   This file automatically generated by Ruby Gem - demake 0.2.4

*/

#ifndef NULL
  #define NULL                          ((void *) 0)
#endif

#define BIT_0                           (1 << 0)
#define BIT_1                           (1 << 1)
#define BIT_2                           (1 << 2)
#define BIT_3                           (1 << 3)

#define NUM_BITS                        4

cc8 bits_list[] = {
  "0",
  "1",
  "2",
  "3",
  NULL
};

#define FLAG_A                          (1 << 0)
#define FLAG_B                          (1 << 1)
#define FLAG_C                          (1 << 2)
#define FLAG_D                          (1 << 3)

#define NUM_FLAGS                       4

cc8 flags_list[] = {
  "A",
  "B",
  "C",
  "D",
  NULL
};
=end
