#file = "auto_list_generated.h"
prefix = "color"
list = [ "blue", "green", "red", "purple" ]
auto_list_add(prefix, list)
#auto_bits_add(prefix, list, file)

prefix = "shape"
list = [ "circle", "triangle", "square", "hexagon" ]
auto_list_add(prefix, list)

@prespace = 0
@target_tab_column = 5
notify("|g|[check mark]|n demake/auto_list.rb is present - generating code")

=begin

The default configuration above generates the following C code
in the file auto_list_generated.h:

/*

   This file automatically generated by Ruby Gem - demake 0.2.4

*/

#ifndef NULL
  #define NULL                          ((void *) 0)
#endif

#define COLOR_BLUE                      0
#define COLOR_GREEN                     1
#define COLOR_RED                       2
#define COLOR_PURPLE                    3

#define NUM_COLORS                      4

cc8 colors_list[] = {
  "blue",
  "green",
  "red",
  "purple",
  NULL
};

#define SHAPE_CIRCLE                    0
#define SHAPE_TRIANGLE                  1
#define SHAPE_SQUARE                    2
#define SHAPE_HEXAGON                   3

#define NUM_SHAPES                      4

cc8 shapes_list[] = {
  "circle",
  "triangle",
  "square",
  "hexagon",
  NULL
};

=end
